//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace CordovaTest.RestServiceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestServiceTest.IRestServiceTest")]
    public interface IRestServiceTest {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRestServiceTest/xmlData", ReplyAction="http://tempuri.org/IRestServiceTest/xmlDataResponse")]
        System.IAsyncResult BeginxmlData(string id, System.AsyncCallback callback, object asyncState);
        
        string EndxmlData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRestServiceTest/JSONData", ReplyAction="http://tempuri.org/IRestServiceTest/JSONDataResponse")]
        System.IAsyncResult BeginJSONData(string id, System.AsyncCallback callback, object asyncState);
        
        string EndJSONData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceTestChannel : CordovaTest.RestServiceTest.IRestServiceTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class xmlDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public xmlDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JSONDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public JSONDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceTestClient : System.ServiceModel.ClientBase<CordovaTest.RestServiceTest.IRestServiceTest>, CordovaTest.RestServiceTest.IRestServiceTest {
        
        private BeginOperationDelegate onBeginxmlDataDelegate;
        
        private EndOperationDelegate onEndxmlDataDelegate;
        
        private System.Threading.SendOrPostCallback onxmlDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginJSONDataDelegate;
        
        private EndOperationDelegate onEndJSONDataDelegate;
        
        private System.Threading.SendOrPostCallback onJSONDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public RestServiceTestClient() {
        }
        
        public RestServiceTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<xmlDataCompletedEventArgs> xmlDataCompleted;
        
        public event System.EventHandler<JSONDataCompletedEventArgs> JSONDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CordovaTest.RestServiceTest.IRestServiceTest.BeginxmlData(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginxmlData(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CordovaTest.RestServiceTest.IRestServiceTest.EndxmlData(System.IAsyncResult result) {
            return base.Channel.EndxmlData(result);
        }
        
        private System.IAsyncResult OnBeginxmlData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return ((CordovaTest.RestServiceTest.IRestServiceTest)(this)).BeginxmlData(id, callback, asyncState);
        }
        
        private object[] OnEndxmlData(System.IAsyncResult result) {
            string retVal = ((CordovaTest.RestServiceTest.IRestServiceTest)(this)).EndxmlData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnxmlDataCompleted(object state) {
            if ((this.xmlDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.xmlDataCompleted(this, new xmlDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void xmlDataAsync(string id) {
            this.xmlDataAsync(id, null);
        }
        
        public void xmlDataAsync(string id, object userState) {
            if ((this.onBeginxmlDataDelegate == null)) {
                this.onBeginxmlDataDelegate = new BeginOperationDelegate(this.OnBeginxmlData);
            }
            if ((this.onEndxmlDataDelegate == null)) {
                this.onEndxmlDataDelegate = new EndOperationDelegate(this.OnEndxmlData);
            }
            if ((this.onxmlDataCompletedDelegate == null)) {
                this.onxmlDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnxmlDataCompleted);
            }
            base.InvokeAsync(this.onBeginxmlDataDelegate, new object[] {
                        id}, this.onEndxmlDataDelegate, this.onxmlDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CordovaTest.RestServiceTest.IRestServiceTest.BeginJSONData(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginJSONData(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CordovaTest.RestServiceTest.IRestServiceTest.EndJSONData(System.IAsyncResult result) {
            return base.Channel.EndJSONData(result);
        }
        
        private System.IAsyncResult OnBeginJSONData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return ((CordovaTest.RestServiceTest.IRestServiceTest)(this)).BeginJSONData(id, callback, asyncState);
        }
        
        private object[] OnEndJSONData(System.IAsyncResult result) {
            string retVal = ((CordovaTest.RestServiceTest.IRestServiceTest)(this)).EndJSONData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnJSONDataCompleted(object state) {
            if ((this.JSONDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.JSONDataCompleted(this, new JSONDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void JSONDataAsync(string id) {
            this.JSONDataAsync(id, null);
        }
        
        public void JSONDataAsync(string id, object userState) {
            if ((this.onBeginJSONDataDelegate == null)) {
                this.onBeginJSONDataDelegate = new BeginOperationDelegate(this.OnBeginJSONData);
            }
            if ((this.onEndJSONDataDelegate == null)) {
                this.onEndJSONDataDelegate = new EndOperationDelegate(this.OnEndJSONData);
            }
            if ((this.onJSONDataCompletedDelegate == null)) {
                this.onJSONDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnJSONDataCompleted);
            }
            base.InvokeAsync(this.onBeginJSONDataDelegate, new object[] {
                        id}, this.onEndJSONDataDelegate, this.onJSONDataCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CordovaTest.RestServiceTest.IRestServiceTest CreateChannel() {
            return new RestServiceTestClientChannel(this);
        }
        
        private class RestServiceTestClientChannel : ChannelBase<CordovaTest.RestServiceTest.IRestServiceTest>, CordovaTest.RestServiceTest.IRestServiceTest {
            
            public RestServiceTestClientChannel(System.ServiceModel.ClientBase<CordovaTest.RestServiceTest.IRestServiceTest> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginxmlData(string id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("xmlData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndxmlData(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("xmlData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginJSONData(string id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("JSONData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndJSONData(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("JSONData", _args, result)));
                return _result;
            }
        }
    }
}
